# Trading_positions Configuration
# Ultra-low latency trading_positions

extends: common_kafka_sink.yaml

# Topic-specific settings
topic:
  name: "trading_positions"

# Topic-specific schema
schema:
  # this type  will always be json for this demo


# Topic properties
topic_config:
  partitions: 3
  retention.ms: 86400000  # 1 day retention